import { loadConfig } from '@/config'
import { asMock } from '@/testing-support'
import { backupFile, backupPrune, dateWithHour } from '@/util'

import { backupBearDatabase } from './backup'

jest.mock('@/util')
jest.mock('@/config')

const mockConfig = {
  bearDatabase: '/path/to/beardb',
  keepBackups: 2,
  rootDir: '/mock/root',
}

beforeEach(() => {
  asMock(loadConfig).mockReturnValue(mockConfig)
  asMock(dateWithHour).mockReturnValue('20240101-11')
})

describe('backupBearDatabase', () => {
  test('calls backupFile with correct arguments', () => {
    backupBearDatabase()

    expect(backupFile).toHaveBeenCalledWith(
      '/path/to/beardb',
      '/mock/root/bear-backups',
      'bear-backup-20240101-11.sqlite'
    )
  })

  test('calls backupPrune with correct arguments', () => {
    backupBearDatabase()

    expect(backupPrune).toHaveBeenCalledWith(
      'bear-backup-',
      '/mock/root/bear-backups',
      2
    )
  })

  test('returns the backup file path generated by the backupFile function', () => {
    asMock(backupFile).mockReturnValue('/backup/target/path')

    const result = backupBearDatabase()

    expect(result).toMatch('/backup/target/path')
  })
})
